backend:
  name: github
  repo: chesteralan/devfolio-gatsbyjs
  branch: main
site_url: https://www.chesteralan.com
display_url: https://www.chesteralan.com
local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: false

collections:
  - name: services
    label: Services
    folder: services
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }