backend:
  name: github
  repo: chesteralan/devfolio-gatsbyjs
  branch: main
site_url: https://www.chesteralan.com
display_url: https://www.chesteralan.com
local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: true

collections:
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "Services"
        name: "services-page"
        file: "static/data/services.json"
        fields:
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: icon, name: icon, widget: string}
      - label: "Portfolio"
        name: "portfolio"
        file: "static/data/portfolio.json"
        fields:
          - label: Portfolio
            name: portfolio
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Category, name: category, widget: string}